# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/devkitpro/msys2/usr/bin/cmake.exe

# The command to remove a file.
RM = /opt/devkitpro/msys2/usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nicol/OneDrive/nicodeGmbH/C-Chip

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nicol/OneDrive/nicodeGmbH/C-Chip

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/devkitpro/msys2/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/devkitpro/msys2/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nicol/OneDrive/nicodeGmbH/C-Chip/CMakeFiles /home/nicol/OneDrive/nicodeGmbH/C-Chip//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nicol/OneDrive/nicodeGmbH/C-Chip/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chip_c

# Build rule for target.
chip_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chip_c
.PHONY : chip_c

# fast build rule for target.
chip_c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip_c.dir/build.make CMakeFiles/chip_c.dir/build
.PHONY : chip_c/fast

include/cJSON.o: include/cJSON.c.o
.PHONY : include/cJSON.o

# target to build an object file
include/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip_c.dir/build.make CMakeFiles/chip_c.dir/include/cJSON.c.o
.PHONY : include/cJSON.c.o

include/cJSON.i: include/cJSON.c.i
.PHONY : include/cJSON.i

# target to preprocess a source file
include/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip_c.dir/build.make CMakeFiles/chip_c.dir/include/cJSON.c.i
.PHONY : include/cJSON.c.i

include/cJSON.s: include/cJSON.c.s
.PHONY : include/cJSON.s

# target to generate assembly for a file
include/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip_c.dir/build.make CMakeFiles/chip_c.dir/include/cJSON.c.s
.PHONY : include/cJSON.c.s

src/frame-to-ascii.o: src/frame-to-ascii.c.o
.PHONY : src/frame-to-ascii.o

# target to build an object file
src/frame-to-ascii.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip_c.dir/build.make CMakeFiles/chip_c.dir/src/frame-to-ascii.c.o
.PHONY : src/frame-to-ascii.c.o

src/frame-to-ascii.i: src/frame-to-ascii.c.i
.PHONY : src/frame-to-ascii.i

# target to preprocess a source file
src/frame-to-ascii.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip_c.dir/build.make CMakeFiles/chip_c.dir/src/frame-to-ascii.c.i
.PHONY : src/frame-to-ascii.c.i

src/frame-to-ascii.s: src/frame-to-ascii.c.s
.PHONY : src/frame-to-ascii.s

# target to generate assembly for a file
src/frame-to-ascii.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip_c.dir/build.make CMakeFiles/chip_c.dir/src/frame-to-ascii.c.s
.PHONY : src/frame-to-ascii.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip_c.dir/build.make CMakeFiles/chip_c.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip_c.dir/build.make CMakeFiles/chip_c.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip_c.dir/build.make CMakeFiles/chip_c.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chip_c"
	@echo "... include/cJSON.o"
	@echo "... include/cJSON.i"
	@echo "... include/cJSON.s"
	@echo "... src/frame-to-ascii.o"
	@echo "... src/frame-to-ascii.i"
	@echo "... src/frame-to-ascii.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

